### ISSUE TITLE
서킷 브레이크 설정

### ISSUE THREAD

**Issue by uttdhk** [uttdhk/PurifierRentalPJT#21]
1. 서킷 브레이크 적용
```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: order
spec:
  host: order
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1           # 목적지로 가는 HTTP, TCP connection 최대 값. (Default 1024)
      http:
        http1MaxPendingRequests: 1  # 연결을 기다리는 request 수를 1개로 제한 (Default 
        maxRequestsPerConnection: 1 # keep alive 기능 disable
        maxRetries: 3               # 기다리는 동안 최대 재시도 수(Default 1024)
    outlierDetection:
      consecutiveErrors: 5          # 5xx 에러가 5번 발생하면
      interval: 1s                  # 1초마다 스캔 하여
      baseEjectionTime: 30s         # 30 초 동안 circuit breaking 처리   
      maxEjectionPercent: 100       # 100% 로 차단
EOF
```

2. seige 명령어로 서킷브레이크 상태 확인
```
siege -c100 -t60S -v 'http://ae725b80f27be48caaea2ae8ed546c7d-1955668814.ap-southeast-2.elb.amazonaws.com:8080/order/joinOrder POST productId=101&productName=PURI1&installationAddress=AWS_Address&customerId=301'
```
![512  02  seige 명령 결과](https://user-images.githubusercontent.com/81424367/120604473-0f867b00-c488-11eb-9575-6d0681075e84.png)

3. kiali에서 서킷브레이크 상태 확인
![512  03  seige 명령 결과(kiali)](https://user-images.githubusercontent.com/81424367/120604477-101f1180-c488-11eb-9bb9-c3077f72ba06.png)

4. 서킷 브레이크 적용 해제
kubectl delete dr --all

5. seige명령어로 서킷브레이크 상태 확인
```
siege -c100 -t60S -v 'http://ae725b80f27be48caaea2ae8ed546c7d-1955668814.ap-southeast-2.elb.amazonaws.com:8080/order/joinOrder POST productId=101&productName=PURI1&installationAddress=AWS_Address&customerId=301'
```
![512  04  destination rule 삭제 후 seige 명령 결과](https://user-images.githubusercontent.com/81424367/120604478-101f1180-c488-11eb-9978-4e2926e0bba3.png)

5. kiali에서 서킷브레이크 상태 확인
![512  05  destination rule 삭제 후 seige 명령 결과(kiali)](https://user-images.githubusercontent.com/81424367/120604482-10b7a800-c488-11eb-941c-3c20479583fe.png)

06  seige 결과(kiali)
![512  06  seige 결과(kiali)](https://user-images.githubusercontent.com/81424367/120731960-8de22c00-c51f-11eb-82bf-0f363858b8a0.png)

07  seige 결과(후기등록)
![512  07  seige 결과(후기등록)](https://user-images.githubusercontent.com/81424367/120731964-8fabef80-c51f-11eb-8693-1bab991ab9b8.png)

08  destination rule 삭제 후 seige 명령 결
![512  08  destination rule 삭제 후 seige 명령 결과](https://user-images.githubusercontent.com/81424367/120731965-8fabef80-c51f-11eb-81f6-b34198bb947f.png)

9.  destination rule 삭제 후 seige 명령 결과
![512  09  destination rule 삭제 후 seige 명령 결과(kiali)](https://user-images.githubusercontent.com/81424367/120731967-90448600-c51f-11eb-90fa-d724c287f9e4.png)
