### ISSUE TITLE
liveness 적용 테스트

### ISSUE THREAD

**Issue by uttdhk** [uttdhk/PurifierRentalPJT#22]
1. customer서비스에 liveness 적용
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: 879772956301.dkr.ecr.ap-southeast-2.amazonaws.com/user13-customer:v2
          args:
          - /bin/sh
          - -c
          - touch /tmp/healthy; sleep 10; rm -rf /tmp/healthy; sleep 600;
          ports:
            - containerPort: 8080
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 3
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

```

2. live적용 시작
![513  04  liveness테스트1(customer)](https://user-images.githubusercontent.com/81424367/120732197-de598980-c51f-11eb-97c0-56cdc6640255.png)

3. live적용 일정 시간 지난 후
![513  04  liveness테스트2(customer)](https://user-images.githubusercontent.com/81424367/120732225-e6b1c480-c51f-11eb-8af1-ccaa7fee8fb0.png)

![513  04  liveness테스트1(customer)](https://user-images.githubusercontent.com/81424367/120748680-27203b00-c53e-11eb-965b-46f918652f46.png)
![513  04  liveness테스트2(customer)](https://user-images.githubusercontent.com/81424367/120748682-27b8d180-c53e-11eb-891a-128a0f267c2a.png)
