### ISSUE TITLE
오토스케일 아웃

### ISSUE THREAD

**Issue by uttdhk** [uttdhk/PurifierRentalPJT#23]
![514  05  쿠버네티스 상태 확인(customer)](https://user-images.githubusercontent.com/81424367/120748490-d6104700-c53d-11eb-9300-41ef48ccd0de.png)
![514  07  autoscalout 확인(customer)](https://user-images.githubusercontent.com/81424367/120748500-d9a3ce00-c53d-11eb-8fb8-db06e59e5715.png)

1.  AutoScaleout

- autoscale 설정
```
kubectl autoscale deploy customer --min=1 --max=10 --cpu-percent=1
```
- autoscale.yml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          resources:
            limits: 
              cpu: 500m
            requests:
              cpu: 200m
          image: 879772956301.dkr.ecr.ap-southeast-2.amazonaws.com/user13-customer:v2
```

2. 오토스케일아웃이 발생하지 않음

![514  01  AutoScaleout](https://user-images.githubusercontent.com/81424367/120621957-5a5cbe80-c499-11eb-932a-e896c737d3a4.png)

3. 메트릭스 서비스 설치
![514  02  메트릭스 설치](https://user-images.githubusercontent.com/81424367/120621965-5b8deb80-c499-11eb-8c5c-3ee3175f72d5.png)

4. 오토스케일아웃 확인
![514  07  autoscalout 확인(customer)](https://user-images.githubusercontent.com/81424367/120732354-1eb90780-c520-11eb-979f-99c61eba1b78.png)

5. deploy 상태 확인
![514  05  쿠버네티스 상태 확인(customer)](https://user-images.githubusercontent.com/81424367/120732519-6fc8fb80-c520-11eb-8b4d-df1b2a572b48.png)

customer
쿠버네티스 상태 확인
![514  05  쿠버네티스 상태 확인(customer)](https://user-images.githubusercontent.com/81424367/120748532-e4f6f980-c53d-11eb-819d-b8e724c9a5df.png)
autoscalout 확인
![514  07  autoscalout 확인(customer)](https://user-images.githubusercontent.com/81424367/120748536-e6282680-c53d-11eb-9431-9a3287da15cd.png)

6. autoscale 설정 해제

```
root@labs--93793215:/home/project/operation# kubectl get hpa
NAME       REFERENCE             TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
customer   Deployment/customer   3%/1%     1         10        10         10m
root@labs--93793215:/home/project/operation# kubectl delete hpa customer
horizontalpodautoscaler.autoscaling "customer" deleted
root@labs--93793215:/home/project/operation# 
```
