### ISSUE TITLE
Secret 적용

### ISSUE THREAD

**Issue by uttdhk** [uttdhk/PurifierRentalPJT#24]
1. base64 암호화
```
root@labs--93793215:/home/project/operation# echo 'Administrator' | base64
QWRtaW5pc3RyYXRvcgo=
root@labs--93793215:/home/project/operation# echo 'pass123456' | base64
cGFzczEyMzQ1Ngo=
```

2. Secret 생성
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: order
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcgo=
  password: cGFzczEyMzQ1Ngo=
EOF
```

3. order 생성 
![515  01  Secret (HTTP POST ORDER)](https://user-images.githubusercontent.com/81424367/120637579-0a3a2800-c4aa-11eb-861d-c1d9b3217d74.png)

4. order 로그 확인
```
kubectl logs pod/order-6d5b449987-nqbws -c order
```
![515  02  Secret (kubectl order 로그 확인](https://user-images.githubusercontent.com/81424367/120637583-0b6b5500-c4aa-11eb-95be-01ee44782b36.png)
